### PR TITLE
Add option to server to get TLS ConnectionState for connections

### PR DESCRIPTION
**Pull request by michaelbeaumont**
This is one way of doing it, another would be to stash the `tls.ConnectionState` in the `WebSocket` and add an accessor.

### CODE REVIEW

**Comment by lorenzodonini** [comment]
I honestly like the second idea better, because it allows to access everything in the same callback. The information can easily be passed all the way to the application. It would be a breaking change in the interface though, so up for debate. Btw I'm currently working on some improvements in the websocket package, so I could add your suggestion there directly in that case.

**Comment by michaelbeaumont** [comment]
So to be clear, adding it to `ws.Channel`? I actually like that option better as well.

**Comment by lorenzodonini** [comment]
> So to be clear, adding it to `ws.Channel`? I actually like that option better as well.

Yes, that's right

**Comment by lorenzodonini** [comment]
Changes look good. The TLS field are not exposed yet to the callback in the `ocpp1.6/2.0` package (only the client ID being passed there). I can take care of it in a follow-up PR, if you want.

**Comment by michaelbeaumont** [comment]
Good point! I can do the PR now, I'll pass the `ws.Channel` to all the `Server` handlers.

**Comment by lorenzodonini** [comment]
> Good point! I can do the PR now, I'll pass the `ws.Channel` to all the `Server` handlers.

I merged this PR in the meantime. 
It's gonna be quite a few changes, since you'll need to change the callback's signature, so I thought it would be best to keep it separate.

**Pull request merged**
