### PR TITLE
Add option to attach disconnect/reconnect handlers to ocppj.Client

### PR DESCRIPTION
**Pull request by michaelbeaumont**

### CODE REVIEW

**Comment by lorenzodonini** [comment]
I'm conflicted about this: the whole idea of automatic reconnection, is to have a transparent mechanism, so the application doesn't even have to know about a disc/reconnection. 

Would you use this for logging purposes and state management only, or are there are use cases?

**Comment by michaelbeaumont** [comment]
Ultimately the use case boils down to needing to know whether I can expect a timely response from the backend or not.

**Review by lorenzodonini — APPROVED** [review]

**Comment by lorenzodonini** [comment]
Approved. There's some conflicts with the other request I merged before.

**Comment by michaelbeaumont** [comment]
@lorenzodonini this can be merged

**Comment by michaelbeaumont** [comment]
Closing, included in https://github.com/lorenzodonini/ocpp-go/pull/117/

**Pull request closed without merging**
