### PR TITLE
add get FormatError method & fix test

### PR DESCRIPTION
**Pull request by dwibudut**
fix error on https://github.com/lorenzodonini/ocpp-go/pull/232

### CODE REVIEW

**Comment by andig** [comment]
Shouldnt this target pr branch? Or is this a different approach?

**Comment by andig** [comment]
Thank you for the fix. It feels wrong to add public Api for this purpose though?

**Comment by dwibudut** [comment]
> Shouldnt this target pr branch? Or is this a different approach?

Hello, I just moved it to the pr target branch. 
https://github.com/andig/ocpp-go/pull/1

**Comment by dwibudut** [comment]
> Thank you for the fix. It feels wrong to add public Api for this purpose though?

I think it's the only way to get the `FormatError` value set on api start.

**Comment by andig** [comment]
@dwibudut though about this some more. Would you be happy with adding 

    types.Dialect int = iota, V16, V20

add that to the endpoint interface and then a 

    ocppj.dialectFormatError() ocpp.ErrorCode

That way the interface would at least be less specific?

**Pull request closed without merging**
