### PR TITLE
Added OCPP 1.6 security extension

### PR DESCRIPTION
**Pull request by xBlaz3kx**
## Proposed changes

- Implemented OCPP 1.6 security extension messages
- Added implementation examples

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of
them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before
merging your code._

- [ ] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

- Code isn't unit tested
- Worked fine in staging/production environment

### CODE REVIEW

**Comment by dwibudut** [comment]
Hi,

Why not use the standard specification for ISO15118 in ocpp1.6, as described in the following document:
https://openchargealliance.org/wp-content/uploads/2023/11/ocpp_1_6_ISO_15118_v10.pdf

**Comment by xBlaz3kx** [comment]
Hey @dwibudut, 

this is the OCPP 1.6 security extension, which includes certificate management feature (TLS/SSL for websockets certificate management as well as ISO 15118 certificate management) among other features. 

I'm not sure what you're trying to say - have I implemented something wrong in regards to certificate management?

**Comment by dwibudut** [comment]
Hi @xBlaz3kx,

There isn't anything wrong. Actually, I'm a little confused about whether the document (version via `DataTransfer`) is for features: for example `CertificateSigned`, `GetInstalledCertificateIds` in document above is no longer valid or only for PnC

**Comment by xBlaz3kx** [comment]
@dwibudut As I said before, this Security extension implementation has little to do with Plug and Charge feature implementation for OCPP 1.6. [Here](https://openchargealliance.org/wp-content/uploads/2023/11/OCPP-1.6-security-whitepaper-edition-3-2.zip) you can find any relevant information regarding this implementation. 

Also, in the PnC specification, this note is applicable: 

image

**Comment by xBlaz3kx** [comment]
Moving to #266

**Pull request closed without merging**
